services:
  kuma-api:
    build:
      context: .
      args:
        BUILDER_IMAGE: ${BUILDER_IMAGE:-docker.m.daocloud.io/library/rust:1}
        RUNTIME_IMAGE: ${RUNTIME_IMAGE:-docker.m.daocloud.io/library/debian:bookworm-slim}
    container_name: kuma-api
    ports:
      - "7788:7788"
    restart: unless-stopped
